# Generated by Django 3.2 on 2021-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Agente'), (3, 'Costos'), (4, 'Direccion'), (6, 'Embarques'), (7, 'Facturacion'), (8, 'Fechas'), (9, 'Ingenieria')], null=True),
        ),
    ]
