# Generated by Django 3.2 on 2021-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('is_active', models.BooleanField(default=True)),
                ('codename', models.CharField(max_length=30, verbose_name='codigo')),
                ('description', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='last modified')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=10, verbose_name='rol')),
                ('permissions', models.ManyToManyField(to='users.Permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
