# Generated by Django 3.2 on 2021-06-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_permissions_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=30, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='rol'),
        ),
    ]
