# Generated by Django 3.2 on 2021-04-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210415_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='rolesito',
        ),
    ]
