# Generated by Django 3.2 on 2021-06-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210605_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['codename', 'description']},
        ),
    ]
