# Generated by Django 3.2 on 2021-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20210415_0814'),
        ('users', '0004_rename_roles_user_rolesito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rolesito',
            field=models.ManyToManyField(blank=True, to='roles.Role'),
        ),
    ]
