# Generated by Django 3.2 on 2021-04-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_rolesito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rolesito',
            new_name='role',
        ),
    ]
