# Generated by Django 3.2 on 2021-06-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',), 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
