# Generated by Django 3.2 on 2021-06-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',), 'verbose_name': 'Role', 'verbose_name_plural': 'roles'},
        ),
    ]
