# Generated by Django 3.2 on 2021-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('representant', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, 
                serialize=False, verbose_name='ID')),
                ('orderBalance', models.CharField(max_length=45)),
                ('factureBalance', models.CharField(max_length=45)),
            ],
        ),
    ]
