# Generated by Django 3.2 on 2021-05-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order_balance', models.CharField(max_length=45)),
                ('facture_balance', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ClientsBalance',
        ),
        migrations.AlterField(
            model_name='agent',
            name='representant',
            field=models.CharField(max_length=45),
        ),
    ]
