# Generated by Django 3.2 on 2021-06-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('companies', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('price_list_id', models.CharField(max_length=10, unique=True)),
                ('discount_level', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('cantOImp', models.BigIntegerField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='prices')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.item', verbose_name='price_lists')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('client_id', models.CharField(max_length=10, unique=True)),
                ('nameA', models.CharField(max_length=50)),
                ('nameB', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Cliente Normal'), (2, 'Cliente Dudoso'), (3, 'Cliene Bloqueado'), (4, 'Cliente Potencia')])),
                ('analist', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('credit_lim', models.BigIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.agent', verbose_name='clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='clients')),
                ('price_list', models.ManyToManyField(to='clients.PriceList', verbose_name='clients')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.warehouse', verbose_name='clients')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
