# Generated by Django 3.2 on 2021-06-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_pricelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='price_list',
            new_name='price_lists',
        ),
    ]
