# Generated by Django 3.2 on 2021-06-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clients', '0003_auto_20210609_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cliente Normal'), (2, 'Cliente Dudoso'), (3, 'Cliente Bloqueado'), (4, 'Cliente Potencia')]),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='price_lists'),
        ),
    ]
