# Generated by Django 3.2 on 2021-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210609_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price_list_id',
            field=models.CharField(max_length=10),
        ),
    ]
