# Generated by Django 3.2 on 2021-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_pricelist_discount_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='discount_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
