# Generated by Django 3.2 on 2021-06-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20210608_1951'),
        ('companies', '0002_alter_company_options'),
        ('clients', '0007_alter_pricelist_discount_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='client',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='clients.agent'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price_lists',
            field=models.ManyToManyField(related_name='clients', to='clients.PriceList'),
        ),
        migrations.AlterField(
            model_name='client',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='inventories.warehouse'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_lists', to='inventories.item'),
        ),
    ]
