# Generated by Django 3.2 on 2021-05-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('item_id', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=70)),
                ('udVta', models.CharField(max_length=4)),
                ('access_key', models.CharField(max_length=20)),
                ('standar_cost', models.DecimalField(decimal_places=4, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
