# Generated by Django 3.2 on 2021-05-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='standar_cost',
            new_name='standard_cost',
        ),
    ]
