# Generated by Django 3.2 on 2021-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='company',
            field=models.CharField(max_length=4, verbose_name='compañia'),
        ),
    ]
