# Generated by Django 3.2 on 2021-06-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_rename_standar_cost_item_standard_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
    ]
