# Generated by Django 3.2 on 2021-04-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_alter_inventory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='almacen',
            field=models.CharField(max_length=4, unique=True, verbose_name='almacen'),
        ),
    ]
