# Generated by Django 3.2 on 2021-04-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20210426_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
