# Generated by Django 3.2 on 2021-04-27 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_alter_warehouse_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=15)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.warehouse')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
