# Generated by Django 3.2 on 2021-04-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='almacen',
            new_name='warehouse',
        ),
    ]
