# Generated by Django 3.2 on 2021-04-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0007_rename_almacen_inventory_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stock',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
    ]
