# Generated by Django 3.2 on 2021-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=False)),
                ('clave', models.CharField(max_length=254, unique=True, verbose_name='clave')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ('id',),
            },
        ),
    ]
