# Generated by Django 3.2 on 2021-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Agente'), (3, 'Costos'), (4, 'Direccion'), (6, 'Embarques'), (7, 'Facturacion'), (8, 'Fechas'), (9, 'Ingenieria')], null=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
