# Generated by Django 3.2 on 2021-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
