# Generated by Django 3.2 on 2021-06-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('vta', models.BooleanField(default=False)),
                ('cst', models.BooleanField(default=False)),
                ('suaje', models.BooleanField(default=False)),
                ('grabado', models.BooleanField(default=False)),
                ('pln', models.BooleanField(default=False)),
                ('ing', models.BooleanField(default=False)),
                ('cxc', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
