# Generated by Django 3.2 on 2021-06-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('companies', '0001_initial'),
        ('clients', '0002_client_pricelist'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('invoice_number', models.BigIntegerField(unique=True)),
                ('position', models.IntegerField()),
                ('delivery', models.IntegerField()),
                ('trans_type', models.CharField(max_length=4)),
                ('invoice_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client', verbose_name='invoices')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='invoices')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.item', verbose_name='invoices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveredQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.BigIntegerField(unique=True)),
                ('position', models.IntegerField()),
                ('mov_date', models.DateField()),
                ('time', models.BigIntegerField()),
                ('sequence', models.IntegerField()),
                ('reg_type', models.IntegerField(choices=[(1, 'Capturado'), (2, 'Cancelado'), (3, 'Facturado')])),
                ('quantity', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='clients')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.item', verbose_name='delivered_quantities')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
