# Generated by Django 3.2 on 2021-06-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210609_0216'),
        ('companies', '0001_initial'),
        ('orders', '0002_deliveredquantity_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveredquantity',
            options={'verbose_name': 'Cantidad Entregada', 'verbose_name_plural': 'Cantidades Entregadas'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.CreateModel(
            name='DeliverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('del_address', models.CharField(max_length=4)),
                ('nameA', models.CharField(blank=True, max_length=50, null=True)),
                ('nameB', models.CharField(blank=True, max_length=50, null=True)),
                ('nameC', models.CharField(blank=True, max_length=50, null=True)),
                ('nameD', models.CharField(blank=True, max_length=50, null=True)),
                ('nameE', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('route_code', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client', verbose_name='del_addresses')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='invoices')),
            ],
            options={
                'verbose_name': 'Direccion de Entrega',
                'verbose_name_plural': 'Direcciones de Entrega',
            },
        ),
    ]
