# Generated by Django 3.2 on 2021-06-09 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clients', '0003_auto_20210609_0216'),
        ('orders', '0003_auto_20210609_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveraddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client', verbose_name='deliver_addresses'),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='deliver_addresses'),
        ),
    ]
