# Generated by Django 3.2 on 2021-06-10 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0004_auto_20210609_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorization',
            options={'verbose_name': 'Authorizaciones', 'verbose_name_plural': 'Listas de Authorizaciones'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Listas de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Listas de Detalles de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Listas de Ventas'},
        ),
        migrations.AlterField(
            model_name='deliveredquantity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='delivered_quantities'),
        ),
    ]
