# Generated by Django 3.2 on 2021-06-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
        ('orders', '0004_auto_20210609_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredquantity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='delivered_quantities'),
        ),
    ]
