# Generated by Django 3.2 on 2021-06-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
        ('clients', '0008_auto_20210610_0814'),
        ('orders', '0005_alter_deliveredquantity_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorization',
            options={'verbose_name': 'Authorizaciones', 'verbose_name_plural': 'Listas de Authorizaciones'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Listas de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Listas de Detalles de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Listas de Ventas'},
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliver_addresses', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='deliveraddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_addresses', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='deliveredquantity',
            name='order',
            field=models.BigIntegerField(),
        ),
    ]
