# Generated by Django 3.2 on 2021-06-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210610_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveraddress',
            name='nameF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
