# Generated by Django 3.2 on 2021-06-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_auto_20210608_1951'),
        ('companies', '0002_alter_company_options'),
        ('orders', '0007_deliveraddress_namef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredquantity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_quantities', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='deliveredquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivered_quantities', to='inventories.item'),
        ),
    ]
