# Generated by Django 3.2 on 2021-06-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210617_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.BigIntegerField(default=0),
        ),
    ]
