# Generated by Django 3.2 on 2021-06-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_invoice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveredquantity',
            name='order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
