# Generated by Django 3.2 on 2021-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_deliveredquantity_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
