# Generated by Django 3.2 on 2021-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_invoice_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.BigIntegerField(),
        ),
    ]
